[package]
name = "tms"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive"] }
clap_complete = "4.0.3"
confy = "0.5.1"
serde = { version = "1.0.147", features = ["derive"] }
